name: test_build

on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build_legacy:
    name: Build on IDF v4.4.6
    runs-on: ubuntu-latest
    container: espressif/idf:v4.4.6
    steps:
      - name: Build idf v4.4.6
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://gitverse.ru{{ github.repository }}.git . || git clone --depth 1 https://gitverse.ru{{ github.repository }}.git .
          . $IDF_PATH/export.sh
          # Список для 4.4.6
          cd examples/hello_world
          idf.py set-target esp32 && idf.py build
          idf.py set-target esp32s2 && idf.py build
          idf.py set-target esp32s3 && idf.py build
          idf.py set-target esp32c3 && idf.py build
          cd ../hello_world_cpp
          idf.py set-target esp32s3 && idf.py build

  build_modern:
    name: Build on IDF v5.1
    runs-on: ubuntu-latest
    container: espressif/idf:v5.1
    steps:
      - name: Build idf v5.1
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://gitverse.ru{{ github.repository }}.git . || git clone --depth 1 https://gitverse.ru{{ github.repository }}.git .
          . $IDF_PATH/export.sh
          # Список для 5.1
          cd examples/hello_world
          idf.py set-target esp32c6 && idf.py build
          cd ../hello_world_cpp
          idf.py set-target esp32c3 && idf.py build
