name: Test Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_esp32:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: esp32,   image: "espressif/idf:v4.4.6", dir: "hello_world" }
          - { target: esp32s2,  image: "espressif/idf:v4.4.6", dir: "hello_world" }
          - { target: esp32s3,  image: "espressif/idf:v4.4.6", dir: "hello_world" }
          - { target: esp32c3,  image: "espressif/idf:v4.4.6", dir: "hello_world" }
          - { target: esp32c6,  image: "espressif/idf:v5.1",   dir: "hello_world" }
          - { target: esp32s3,  image: "espressif/idf:v4.4.6", dir: "hello_world_cpp" }
          - { target: esp32c3,  image: "espressif/idf:v5.1",   dir: "hello_world_cpp" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            ${{ matrix.image }} \
            /bin/bash -c "git config --global --add safe.directory /project && . \$IDF_PATH/export.sh && cd examples/${{ matrix.dir }} && idf.py set-target ${{ matrix.target }} && idf.py build"